# I -  Tensorflow & Keras

<center><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--O_kCr-s2--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/lkli02223oqhlac1jetz.png" style="width:800px;"/></center>


## Ejemplo I: Regla XOR en Tensorflow c/ Keras

In [1]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import binary_crossentropy

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(1234)

In [2]:
epochs = 500
learning_rate = 0.01

In [3]:
#input_data = [[0., 0.], [0., 1.], [1., 0.], [1., 1.]]  # XOR input
#output_data = [[1, 0], [0, 1], [0, 1], [1, 0]]  # XOR output
input_data = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])  # XOR input
output_data = np.array([[1, 0], [0, 1], [0, 1], [1, 0]])  # XOR output

output_classes = 2

In [4]:
# Model
#---------------------------------------------------------------------#
input_layer = Input(shape=(2,))
dense_0 = Dense(10, activation='relu') (input_layer)
dense_1 = Dense(10, activation='relu') (dense_0)
dense_2 = Dense(10, activation='relu') (dense_1)
output_layer = Dense(output_classes, activation='softmax') (dense_2)
#---------------------------------------------------------------------#
model = Model(input_layer, output_layer)

In [5]:
adam_optimizer = Adam(learning_rate=learning_rate)
model.compile(optimizer=adam_optimizer, loss='binary_crossentropy')
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 2)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10)             │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 2)              │            22 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 272 (1.06 KB)

 Trainable params: 272 (1.06 KB)

 Non-trainable params: 0 (0.00 B)

In [6]:
history = model.fit(input_data, output_data, epochs=epochs, verbose=1)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - loss: 0.6964
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step - loss: 0.6851
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - loss: 0.6750
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - loss: 0.6646
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - loss: 0.6543
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - loss: 0.6439
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 320ms/step - loss: 0.6332
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - loss: 0.6209
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 272ms/step - loss: 0.6071
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - loss: 0.5924
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.5778
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 352ms/step - loss: 0.5617
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - loss: 0.5444
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.5268
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 0.5091
Epoch 16

In [7]:
f = plt.figure(figsize=(10,10))
plt.plot(history.history['loss'], linewidth=3, label='Train loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend(loc='upper right')

In [10]:
#model.predict([[0., 0.], [0., 1.], [1., 0.], [1., 1.]], verbose=1)
model.predict(np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]]), verbose=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step


array([[1.0000000e+00, 1.5539195e-08],
       [1.7967340e-10, 1.0000000e+00],
       [7.7173201e-10, 1.0000000e+00],
       [1.0000000e+00, 5.2398960e-11]], dtype=float32)

## Ejemplo II: Regla XOR en Tensorflow

In [11]:
import tensorflow as tf

In [12]:
def dense( inputs , weights, bias):
    layer = tf.matmul(inputs, weights) + bias
    return tf.nn.relu(layer)

In [13]:
def get_weight( shape , name ):
    return tf.Variable(tf.random.truncated_normal(shape,stddev=0.1), name=name, trainable=True, dtype=tf.float32)

shapes = [[ 2 , 10 ] ,             #0
          [ 10 , 10 ] ,            #1
          [ 10 , 10 ] ,            #2
          [ 10 , output_classes ]] #3

weights = []
bias = []
for i in range( len( shapes ) ):
    weights.append( get_weight( shapes[ i ] , 'weight{}'.format( i ) ) )

for i in range( len( shapes ) ):
    bias.append( get_weight( [1,shapes[i][-1]], 'bias{}'.format( i ) ) )

In [14]:
def trainable_variables():
    return weights + bias

In [15]:
print(weights)

[<tf.Variable 'weight0:0' shape=(2, 10) dtype=float32, numpy=
array([[ 0.10555247, -0.1438093 , -0.04279649,  0.14904861,  0.0318532 ,
         0.03411446,  0.06985759,  0.05102892, -0.03162068,  0.06225894],
       [ 0.01498569,  0.06665373, -0.12263101,  0.02325795, -0.09266463,
         0.01896876,  0.07996684,  0.02956734, -0.15926997, -0.05218005]],
      dtype=float32)>, <tf.Variable 'weight1:0' shape=(10, 10) dtype=float32, numpy=
array([[ 0.02391917, -0.00454312,  0.19521269,  0.08007832,  0.05597046,
         0.02316555,  0.06800447,  0.05397134,  0.17965256,  0.09127148],
       [-0.16421136, -0.05380319,  0.04931169,  0.17031239,  0.1503336 ,
        -0.0102577 , -0.08655339, -0.05989262, -0.06499714, -0.16805592],
       [ 0.09420877,  0.11501401,  0.03247004, -0.11269983, -0.08279347,
         0.03764356,  0.14844324, -0.11011612,  0.06736324,  0.06132365],
       [-0.06952374,  0.05355349,  0.11869305, -0.07696193, -0.18793392,
        -0.0146874 ,  0.07205959,  0.1354001

In [16]:
def model( x ) :
    x = tf.cast( x , dtype=tf.float32 )
    d0 = dense(  x, weights[0], bias[0] )
    d1 = dense( d0, weights[1], bias[1] )
    d2 = dense( d1, weights[2], bias[2] )
    d3 = tf.matmul(d2 , weights[3]) + bias[3]
    return tf.nn.softmax( d3 )

In [17]:
def loss( pred , target ):
    return tf.losses.binary_crossentropy( target , pred )

optimizer = tf.optimizers.Adam( learning_rate )

def train_step( model, inputs , outputs ):
    with tf.GradientTape() as tape:
        current_loss = loss( model( inputs ), outputs)
    grads = tape.gradient( current_loss , trainable_variables() )
    optimizer.apply_gradients( zip( grads , trainable_variables() ) )
    print( tf.reduce_mean( current_loss ) )

In [18]:
for e in range( epochs ):
    train_step( model, input_data , output_data )

tf.Tensor(0.69383883, shape=(), dtype=float32)
tf.Tensor(0.6932465, shape=(), dtype=float32)
tf.Tensor(0.6930961, shape=(), dtype=float32)
tf.Tensor(0.69318646, shape=(), dtype=float32)
tf.Tensor(0.69323766, shape=(), dtype=float32)
tf.Tensor(0.69305754, shape=(), dtype=float32)
tf.Tensor(0.692814, shape=(), dtype=float32)
tf.Tensor(0.6925715, shape=(), dtype=float32)
tf.Tensor(0.6923193, shape=(), dtype=float32)
tf.Tensor(0.6921464, shape=(), dtype=float32)
tf.Tensor(0.69194824, shape=(), dtype=float32)
tf.Tensor(0.6914041, shape=(), dtype=float32)
tf.Tensor(0.6908518, shape=(), dtype=float32)
tf.Tensor(0.69006217, shape=(), dtype=float32)
tf.Tensor(0.68904024, shape=(), dtype=float32)
tf.Tensor(0.68786865, shape=(), dtype=float32)
tf.Tensor(0.68627954, shape=(), dtype=float32)
tf.Tensor(0.68436843, shape=(), dtype=float32)
tf.Tensor(0.6820084, shape=(), dtype=float32)
tf.Tensor(0.67981535, shape=(), dtype=float32)
tf.Tensor(0.6767552, shape=(), dtype=float32)
tf.Tensor(0.6732869, sha

In [19]:
print(weights)

[<tf.Variable 'weight0:0' shape=(2, 10) dtype=float32, numpy=
array([[ 0.39576203, -0.1438093 , -0.04279649,  0.39734274, -0.51446897,
         0.03411446,  0.42880455,  0.45815694, -0.03162068,  0.44576088],
       [ 0.39578542,  0.06665373, -0.12263101,  0.39731732, -0.51445854,
         0.01896876,  0.45774812,  0.4575576 , -0.15926997,  0.37040287]],
      dtype=float32)>, <tf.Variable 'weight1:0' shape=(10, 10) dtype=float32, numpy=
array([[ 8.91981721e-01,  7.07906842e-01,  9.76827681e-01,
         8.00783187e-02, -2.17734557e-02, -7.19255567e-01,
         7.53757834e-01,  8.54328930e-01,  1.79652557e-01,
         3.97329554e-02],
       [-1.64211363e-01, -5.38031869e-02,  4.93116863e-02,
         1.70312390e-01,  1.50333598e-01, -1.02576986e-02,
        -8.65533873e-02, -5.98926209e-02, -6.49971366e-02,
        -1.68055922e-01],
       [ 9.42087695e-02,  1.15014009e-01,  3.24700437e-02,
        -1.12699829e-01, -8.27934667e-02,  3.76435556e-02,
         1.48443237e-01, -1.101161

In [20]:
model([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[9.9988341e-01, 1.1654033e-04],
       [4.4726989e-05, 9.9995530e-01],
       [3.9534472e-05, 9.9996042e-01],
       [9.9995363e-01, 4.6428333e-05]], dtype=float32)>